### ISSUE TITLE
Inputting wrong path in API causes Jupyter kernel to crash

### ISSUE THREAD

**Issue by lanalex** [visualdatabase/fastdup#1]
First I want to say its a great tool and super fast! I used to analyze 19,000 images. The install was fast and the analysis super fast. 
Entering a wrong path (in the input dir) causes a complete kernel crash. I noticed my typo and fixed it. It would be good if the library would return a clearer exception specifying the path doesn't exist.  I haven't tested inputting a none existing dir in the output one.

**Comment by dbickson** [comment]
Hi Alex, 
Thanks for reporting the issue, we have just released version 0.96 to fix it.

Please note that since fastdup is written in c++ sometimes the output is not fully received in the jupyter notebook whenever there is a crash.
There are a couple of options to debug a crash: 
* run in a terminal using verbose=1 and send us the output including your os and fastdup version.
* or run in a jupyter notebook but run using `!python3.8 -c "import fastdup; fastdup.run(....)"` and then you will get the output to see the issue.
