### ISSUE TITLE
unable to install (pip install fastdup==0.132) in windows

### ISSUE THREAD

**Issue by Xnsam** [visualdatabase/fastdup#12]
Hi,

I am unable to install the package on windows for some reason. I could install the package in Linux os.

I checked if I can install other packages and it works, is it some registry issue?

please help

![image](https://user-images.githubusercontent.com/23662182/185433643-33fee3cb-f857-48bd-a02f-f89dc54ff4fe.png)

**Comment by dbickson** [comment]
HI @Xnsam the short answer is that windows is not currently supported.
The longer answer, is that since we have a c++ engine we need to compile it to each platform. It will take us a few weeks of work to compile for Windows and so far there was not enough demand. What you can do is to install docker on windows and download ubuntu, then run fastdup inside the docker.
