### ISSUE TITLE
Error when importing fastdup in docker

### ISSUE THREAD

**Issue by sergii-bond** [visualdatabase/fastdup#3]
The docker image has been built from this repo's [Dockerfile](https://github.com/visualdatabase/fastdup/blob/80fc1b26f07054af58e7e6141cf910869f7e5b1b/Dockerfile).

`import fastdup` returns an error:
```
root@a5a6305aaaf2:/opt# python3.8 
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastdup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fastdup/__init__.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by dbickson** [comment]
Hi Sergei, we have pushed a new version of the docker which is supposed to for this. Not sure why this happened since on our ed it did work even before:
<img width="983" alt="Screen Shot 2022-06-29 at 5 25 12" src="https://user-images.githubusercontent.com/4495523/176337975-4d1f690e-8a71-41a6-aa18-ec9950d6fd24.png">
Please try and let us know if this works.

**Comment by sergii-bond** [comment]
It can import fastdup in docker now, thank you.
